# file ~/Sites/blog/config/packages/monolog.yaml

monolog:
    channels: ['main', 'tools', 'error', 'sso']

    handlers:

        # main application log
        main:
            type: rotating_file
            path: '%kernel.project_dir%/logs/main.log'
            level: debug
            max_files: 30
            channels: [ "!event", "!doctrine", "!console", "!php", "!deprecation" ]
            formatter: 'App\Monolog\ToolsLineFormatter'
            filename_format: '{date}-main'
            date_format: 'Y-m-d'

        # tools handler configures the logs managed by the ToolsController
        tools:
            type: rotating_file
            path: '%kernel.project_dir%/logs/tools.log'
            level: info
            max_files: 30
            channels: ['tools']
            formatter: 'App\Monolog\ToolsLineFormatter'
            filename_format: '{date}-tools'
            date_format: 'Y-m-d'

        # error handler configures the logs managed by the ErrorController
        error:
            type: rotating_file
            path: '%kernel.project_dir%/logs/error.log'
            level: info
            max_files: 30
            channels: [ 'error' ]
            formatter: 'App\Monolog\ToolsLineFormatter'
            filename_format: '{date}-error'
            date_format: 'Y-m-d'

        # sso handler configures the logs managed by the whole SSO system (federated login/logout_
        sso:
            type: rotating_file
            path: '%kernel.project_dir%/logs/sso.log'
            level: info
            max_files: 30
            channels: [ 'sso' ]
            formatter: 'App\Monolog\ToolsLineFormatter'
            filename_format: '{date}-sso'
            date_format: 'Y-m-d'
